import asyncio
import json
from pathlib import Path

from extract import extract_document
from script_gen import generate_curriculum
from tts import generate_audio
from visual import generate_visual
from assemble import make_slide_clip, assemble_video
from lecture_adapter import build_scenes_from_lecture


def _render_scenes(scenes, job: Path, voice: str) -> str:
    """Shared rendering loop: narrate + draw + assemble a list of scenes
    into a single output.mp4 inside `job`."""
    assets = job / "assets"
    assets.mkdir(parents=True, exist_ok=True)

    metadata = {
        "totalScenes": len(scenes),
        "scenes": scenes,
    }
    (job / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    clips = []
    for index, scene in enumerate(scenes):
        script = scene.get("narration", "").strip()
        title = scene.get("title", f"Scene {index + 1}")

        audio_path = assets / f"scene_{index + 1}.wav"
        image_path = assets / f"scene_{index + 1}.png"

        asyncio.run(generate_audio(script, str(audio_path), voice))
        generate_visual(title, scene, str(image_path))

        clips.append(make_slide_clip(str(image_path), str(audio_path)))

    output_path = job / "output.mp4"
    try:
        assemble_video(clips, str(output_path))
    finally:
        for clip in clips:
            try:
                if clip.audio:
                    clip.audio.close()
                clip.close()
            except Exception:
                pass

    return str(output_path)


def run_pipeline(input_path: str, job_dir: str, options=None):
    """Original flow: uploaded PPTX/PDF/TXT -> extract text -> generate a
    curriculum (Ollama or offline fallback) -> render."""
    options = options or {}
    job = Path(job_dir)

    pages = extract_document(input_path)
    if not pages:
        raise ValueError("No readable pages/slides were found in the uploaded file.")

    full_text = "\n\n".join(
        [p.get("text", "").strip() for p in pages if p.get("text", "").strip()]
    ).strip()
    if not full_text:
        raise ValueError("Could not extract readable text from document.")

    scenes = generate_curriculum(full_text, options)
    if not scenes:
        raise ValueError("Failed to generate educational video scenes.")

    return _render_scenes(scenes, job, options.get("voice", "default"))


def run_lecture_pipeline(lecture: dict, job_dir: str, options=None):
    """New flow: a lecture already generated by the Gemini-powered
    "Remix Teacher Lecture Video Generator" UI (slides, bullets, teacher
    script) is rendered directly into a real MP4, skipping document
    extraction and curriculum generation entirely."""
    options = options or {}
    job = Path(job_dir)

    scenes = build_scenes_from_lecture(lecture or {})
    if not scenes:
        raise ValueError("The lecture had no slides to render.")

    return _render_scenes(scenes, job, options.get("voice", "default"))
